[
  {
    "id": 1,
    "entityType": "type",
    "code": "1",
    "number": 10000,
    "name": "ASSETS",
    "finDocName": "BALANCE SHEET",
    "sortOrder": 1,
    "DRCRCode": "DR",
    "filePath": [
      1
    ],
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 2,
    "entityType": "type",
    "code": "2",
    "number": 20000,
    "name": "LIABILITIES",
    "finDocName": "BALANCE SHEET",
    "sortOrder": 2,
    "DRCRCode": "CR",
    "filePath": [
      2
    ],
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 3,
    "entityType": "type",
    "code": "3",
    "number": 30000,
    "name": "EQUITY",
    "finDocName": "BALANCE SHEET",
    "sortOrder": 3,
    "DRCRCode": "CR",
    "filePath": [
      3
    ],
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 21,
    "defaultId": 1,
    "indelible": true,
    "entityType": "class",
    "companyId": 90,
    "typeId": 1,
    "code": "1.1",
    "name": "CURRENT ASSETS",
    "number": "10100",
    "contra": 0,
    "DRCRCode": "DR",
    "clashflowId": 1,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.235Z",
    "updatedDate": null,
    "filePath": [
      1,
      21
    ],
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 22,
    "defaultId": 2,
    "indelible": true,
    "entityType": "class",
    "companyId": 90,
    "typeId": 1,
    "code": "1.2",
    "name": "INVESTMENT",
    "number": "10200",
    "contra": 0,
    "DRCRCode": "DR",
    "clashflowId": 2,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.235Z",
    "updatedDate": null,
    "filePath": [
      1,
      22
    ],
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 23,
    "defaultId": 3,
    "indelible": true,
    "entityType": "class",
    "companyId": 90,
    "typeId": 1,
    "code": "1.3",
    "name": "FIXED ASSETS OR PROPERTY, PLANT & EQUIPMENT",
    "number": "10300",
    "contra": 0,
    "DRCRCode": "DR",
    "clashflowId": 2,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.236Z",
    "updatedDate": null,
    "filePath": [
      1,
      23
    ],
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 24,
    "defaultId": 4,
    "indelible": true,
    "entityType": "class",
    "companyId": 90,
    "typeId": 1,
    "code": "1.4",
    "name": "INTANGIBLE ASSETS",
    "number": "10400",
    "contra": 0,
    "DRCRCode": "DR",
    "clashflowId": 2,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.236Z",
    "updatedDate": null,
    "filePath": [
      1,
      24
    ],
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 25,
    "defaultId": 5,
    "indelible": true,
    "entityType": "class",
    "companyId": 90,
    "typeId": 1,
    "code": "1.5",
    "name": "OTHER ASSETS",
    "number": "10500",
    "contra": 0,
    "DRCRCode": "DR",
    "clashflowId": 2,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.236Z",
    "updatedDate": null,
    "filePath": [
      1,
      25
    ],
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 26,
    "defaultId": 6,
    "indelible": true,
    "entityType": "class",
    "companyId": 90,
    "typeId": 2,
    "code": "2.1",
    "name": "CURRENT LIABILITIES",
    "number": "20100",
    "contra": 0,
    "DRCRCode": "CR",
    "clashflowId": 1,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.236Z",
    "updatedDate": null,
    "filePath": [
      2,
      26
    ],
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 27,
    "defaultId": 7,
    "indelible": true,
    "entityType": "class",
    "companyId": 90,
    "typeId": 2,
    "code": "2.3",
    "name": "LONG TERM LIABILITIES",
    "number": "20300",
    "contra": 0,
    "DRCRCode": "CR",
    "clashflowId": 3,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.236Z",
    "updatedDate": null,
    "filePath": [
      2,
      27
    ],
    "clashflowObj": {
      "id": 3,
      "name": "Financing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 28,
    "defaultId": 8,
    "indelible": true,
    "entityType": "class",
    "companyId": 90,
    "typeId": 2,
    "code": "2.4",
    "name": "OTHER  LIABILITIES",
    "number": "20400",
    "contra": 0,
    "DRCRCode": "CR",
    "clashflowId": 3,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.236Z",
    "updatedDate": null,
    "filePath": [
      2,
      28
    ],
    "clashflowObj": {
      "id": 3,
      "name": "Financing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 29,
    "defaultId": 9,
    "indelible": true,
    "entityType": "class",
    "companyId": 90,
    "typeId": 3,
    "code": "3.1",
    "name": "OPENING BALANCE EQUITY",
    "number": "30100",
    "contra": 0,
    "DRCRCode": "CR",
    "clashflowId": 3,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.236Z",
    "updatedDate": null,
    "filePath": [
      3,
      29
    ],
    "clashflowObj": {
      "id": 3,
      "name": "Financing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 30,
    "defaultId": 10,
    "indelible": true,
    "entityType": "class",
    "companyId": 90,
    "typeId": 3,
    "code": "3.2",
    "name": "OWNER'S EQUITY",
    "number": "30200",
    "contra": 0,
    "DRCRCode": "CR",
    "clashflowId": 3,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.236Z",
    "updatedDate": null,
    "filePath": [
      3,
      30
    ],
    "clashflowObj": {
      "id": 3,
      "name": "Financing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 31,
    "defaultId": 11,
    "indelible": true,
    "entityType": "class",
    "companyId": 90,
    "typeId": 3,
    "code": "3.3",
    "name": "PARTNER'S EQUITY",
    "number": "30300",
    "contra": 0,
    "DRCRCode": "CR",
    "clashflowId": 3,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.236Z",
    "updatedDate": null,
    "filePath": [
      3,
      31
    ],
    "clashflowObj": {
      "id": 3,
      "name": "Financing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 32,
    "defaultId": 12,
    "indelible": true,
    "entityType": "class",
    "companyId": 90,
    "typeId": 3,
    "code": "3.4",
    "name": "STOCKHOLDER'S EQUITY",
    "number": "30400",
    "contra": 0,
    "DRCRCode": "CR",
    "clashflowId": 3,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.236Z",
    "updatedDate": null,
    "filePath": [
      3,
      32
    ],
    "clashflowObj": {
      "id": 3,
      "name": "Financing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 33,
    "defaultId": 13,
    "indelible": true,
    "entityType": "class",
    "companyId": 90,
    "typeId": 3,
    "code": "3.5",
    "name": "RETAINED EARNINGS",
    "number": "30500",
    "contra": 0,
    "DRCRCode": "CR",
    "clashflowId": 3,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.236Z",
    "updatedDate": null,
    "filePath": [
      3,
      33
    ],
    "clashflowObj": {
      "id": 3,
      "name": "Financing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 48,
    "defaultClassId": 1,
    "defaultId": 1,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 21,
    "clashflowId": 0,
    "contra": false,
    "active": true,
    "code": "1.1.1",
    "name": "CASH AND CASH EQUIVALENTS",
    "number": null,
    "DRCRCode": "DR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      1,
      21,
      48
    ],
    "remarks": null,
    "clashflowObj": null,
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 49,
    "defaultClassId": 1,
    "defaultId": 2,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 21,
    "clashflowId": 1,
    "contra": false,
    "active": true,
    "code": "1.1.2",
    "name": "SHORT TERM INVESTMENT",
    "number": null,
    "DRCRCode": "DR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      1,
      21,
      49
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 50,
    "defaultClassId": 1,
    "defaultId": 3,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "SALES",
    "companyId": 90,
    "classId": 21,
    "clashflowId": 1,
    "contra": false,
    "active": true,
    "code": "1.1.3",
    "name": "RECEIVABLES",
    "number": null,
    "DRCRCode": "DR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      1,
      21,
      50
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 51,
    "defaultClassId": 1,
    "defaultId": 4,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 21,
    "clashflowId": 1,
    "contra": false,
    "active": true,
    "code": "1.1.4",
    "name": "RECEIVABLES NON-TRADE",
    "number": null,
    "DRCRCode": "DR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      1,
      21,
      51
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 52,
    "defaultClassId": 1,
    "defaultId": 5,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 21,
    "clashflowId": 1,
    "contra": false,
    "active": true,
    "code": "1.1.5",
    "name": "INVENTORY",
    "number": null,
    "DRCRCode": "DR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      1,
      21,
      52
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 53,
    "defaultClassId": 1,
    "defaultId": 6,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 21,
    "clashflowId": 1,
    "contra": false,
    "active": true,
    "code": "1.1.6",
    "name": "PREPAYMENTS",
    "number": null,
    "DRCRCode": "DR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      1,
      21,
      53
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 54,
    "defaultClassId": 1,
    "defaultId": 7,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 21,
    "clashflowId": 1,
    "contra": false,
    "active": true,
    "code": "1.1.7",
    "name": "OTHER CURRENT ASSETS",
    "number": null,
    "DRCRCode": "DR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      1,
      21,
      54
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 55,
    "defaultClassId": 2,
    "defaultId": 8,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 22,
    "clashflowId": 2,
    "contra": false,
    "active": true,
    "code": "1.2.1",
    "name": "INVESTMENT IN STOCKS",
    "number": null,
    "DRCRCode": "DR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      1,
      22,
      55
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 56,
    "defaultClassId": 2,
    "defaultId": 9,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 22,
    "clashflowId": 2,
    "contra": false,
    "active": true,
    "code": "1.2.2",
    "name": "INVESTMENT IN BONDS",
    "number": null,
    "DRCRCode": "DR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      1,
      22,
      56
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 57,
    "defaultClassId": 3,
    "defaultId": 10,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 23,
    "clashflowId": 2,
    "contra": false,
    "active": true,
    "code": "1.3.1",
    "name": "LAND",
    "number": null,
    "DRCRCode": "DR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      1,
      23,
      57
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 58,
    "defaultClassId": 3,
    "defaultId": 11,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 23,
    "clashflowId": 2,
    "contra": false,
    "active": true,
    "code": "1.3.2",
    "name": "BUILDING",
    "number": null,
    "DRCRCode": "DR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      1,
      23,
      58
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 59,
    "defaultClassId": 3,
    "defaultId": 12,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 23,
    "clashflowId": 2,
    "contra": false,
    "active": true,
    "code": "1.3.3",
    "name": "OFFICE EQUIPMENT",
    "number": null,
    "DRCRCode": "DR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      1,
      23,
      59
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 60,
    "defaultClassId": 3,
    "defaultId": 13,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 23,
    "clashflowId": 2,
    "contra": false,
    "active": true,
    "code": "1.3.4",
    "name": "FURNITURE AND FIXTURES",
    "number": null,
    "DRCRCode": "DR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      1,
      23,
      60
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 61,
    "defaultClassId": 3,
    "defaultId": 14,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 23,
    "clashflowId": 2,
    "contra": false,
    "active": true,
    "code": "1.3.5",
    "name": "TRANSPORTATION EQUIPMENT",
    "number": null,
    "DRCRCode": "DR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      1,
      23,
      61
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 62,
    "defaultClassId": 4,
    "defaultId": 15,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 24,
    "clashflowId": 2,
    "contra": false,
    "active": true,
    "code": "1.4.1",
    "name": "COPYRIGHT",
    "number": null,
    "DRCRCode": "DR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      1,
      24,
      62
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 63,
    "defaultClassId": 4,
    "defaultId": 16,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 24,
    "clashflowId": 2,
    "contra": false,
    "active": true,
    "code": "1.4.2",
    "name": "PATENTS",
    "number": null,
    "DRCRCode": "DR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      1,
      24,
      63
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 64,
    "defaultClassId": 4,
    "defaultId": 17,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 24,
    "clashflowId": 2,
    "contra": false,
    "active": true,
    "code": "1.4.3",
    "name": "RESEARCH AND DEVELOPMENT",
    "number": null,
    "DRCRCode": "DR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      1,
      24,
      64
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 65,
    "defaultClassId": 4,
    "defaultId": 18,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 24,
    "clashflowId": 2,
    "contra": false,
    "active": true,
    "code": "1.4.4",
    "name": "TRADEMARKS",
    "number": null,
    "DRCRCode": "DR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      1,
      24,
      65
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 66,
    "defaultClassId": 5,
    "defaultId": 19,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 25,
    "clashflowId": 2,
    "contra": false,
    "active": true,
    "code": "1.5.1",
    "name": "BANK GUARANTEE",
    "number": null,
    "DRCRCode": "DR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      1,
      25,
      66
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 67,
    "defaultClassId": 6,
    "defaultId": 20,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "PURCHASE",
    "companyId": 90,
    "classId": 26,
    "clashflowId": 1,
    "contra": false,
    "active": true,
    "code": "2.1.1",
    "name": "ACCOUNTS PAYABLE",
    "number": null,
    "DRCRCode": "CR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      2,
      26,
      67
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 68,
    "defaultClassId": 6,
    "defaultId": 21,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 26,
    "clashflowId": 1,
    "contra": false,
    "active": true,
    "code": "2.1.2",
    "name": "ACCRUED EXPENSES",
    "number": null,
    "DRCRCode": "CR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      2,
      26,
      68
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 69,
    "defaultClassId": 6,
    "defaultId": 22,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 26,
    "clashflowId": 1,
    "contra": false,
    "active": true,
    "code": "2.1.3",
    "name": "NOTES PAYABLE",
    "number": null,
    "DRCRCode": "CR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      2,
      26,
      69
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 70,
    "defaultClassId": 6,
    "defaultId": 23,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 26,
    "clashflowId": 1,
    "contra": false,
    "active": true,
    "code": "2.1.4",
    "name": "SALARIES PAYABLE",
    "number": null,
    "DRCRCode": "CR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      2,
      26,
      70
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 71,
    "defaultClassId": 6,
    "defaultId": 24,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 26,
    "clashflowId": 1,
    "contra": false,
    "active": true,
    "code": "2.1.5",
    "name": "SALARIES STATUTORY PAYABLE",
    "number": null,
    "DRCRCode": "CR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      2,
      26,
      71
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 72,
    "defaultClassId": 6,
    "defaultId": 25,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 26,
    "clashflowId": 1,
    "contra": false,
    "active": true,
    "code": "2.1.6",
    "name": "DIRECT DEPOSIT LIABILITIES",
    "number": null,
    "DRCRCode": "CR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      2,
      26,
      72
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 73,
    "defaultClassId": 6,
    "defaultId": 26,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 26,
    "clashflowId": 1,
    "contra": false,
    "active": true,
    "code": "2.2.1",
    "name": "OTHER  CURRENT LIABILITIES",
    "number": null,
    "DRCRCode": "CR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      2,
      26,
      73
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 74,
    "defaultClassId": 7,
    "defaultId": 27,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 27,
    "clashflowId": 3,
    "contra": false,
    "active": true,
    "code": "2.3.1",
    "name": "LONG TERM PAYABLE",
    "number": null,
    "DRCRCode": "CR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      2,
      27,
      74
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 3,
      "name": "Financing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 75,
    "defaultClassId": 8,
    "defaultId": 28,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 28,
    "clashflowId": 3,
    "contra": false,
    "active": true,
    "code": "2.4.1",
    "name": "OTHER LIABILITIES",
    "number": null,
    "DRCRCode": "CR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      2,
      28,
      75
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 3,
      "name": "Financing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 76,
    "defaultClassId": 9,
    "defaultId": 29,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 29,
    "clashflowId": 3,
    "contra": false,
    "active": true,
    "code": "3.1.1",
    "name": "OPENING BALANCE EQUITY",
    "number": null,
    "DRCRCode": "CR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      3,
      29,
      76
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 3,
      "name": "Financing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 77,
    "defaultClassId": 10,
    "defaultId": 30,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 30,
    "clashflowId": 3,
    "contra": false,
    "active": true,
    "code": "3.2.1",
    "name": "OWNER'S EQUITY",
    "number": null,
    "DRCRCode": "CR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      3,
      30,
      77
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 3,
      "name": "Financing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 78,
    "defaultClassId": 10,
    "defaultId": 31,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 30,
    "clashflowId": 3,
    "contra": true,
    "active": true,
    "code": "3.2.2",
    "name": "OWNER'S WITHDRAWAL",
    "number": null,
    "DRCRCode": "DR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      3,
      30,
      78
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 3,
      "name": "Financing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 79,
    "defaultClassId": 11,
    "defaultId": 32,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 31,
    "clashflowId": 3,
    "contra": false,
    "active": true,
    "code": "3.3.1",
    "name": "PARTNER'S CAPITAL",
    "number": null,
    "DRCRCode": "CR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      3,
      31,
      79
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 3,
      "name": "Financing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 80,
    "defaultClassId": 11,
    "defaultId": 33,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 31,
    "clashflowId": 3,
    "contra": true,
    "active": true,
    "code": "3.3.2",
    "name": "PARTNER'S WITHDRAWAL",
    "number": null,
    "DRCRCode": "DR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      3,
      31,
      80
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 3,
      "name": "Financing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 81,
    "defaultClassId": 12,
    "defaultId": 34,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 32,
    "clashflowId": 3,
    "contra": false,
    "active": true,
    "code": "3.4.1",
    "name": "CAPITAL STOCK",
    "number": null,
    "DRCRCode": "CR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      3,
      32,
      81
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 3,
      "name": "Financing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 82,
    "defaultClassId": 13,
    "defaultId": 35,
    "indelible": true,
    "entityType": "group",
    "transactionCode": "GENERAL",
    "companyId": 90,
    "classId": 33,
    "clashflowId": 3,
    "contra": false,
    "active": true,
    "code": "3.5.1",
    "name": "RETAINED EARNINGS",
    "number": null,
    "DRCRCode": "CR",
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.280Z",
    "updatedDate": null,
    "filePath": [
      3,
      33,
      82
    ],
    "remarks": null,
    "clashflowObj": {
      "id": 3,
      "name": "Financing"
    },
    "report": "BS",
    "nameTax": "No tax"
  },
  {
    "id": 101,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": -93405.6,
    "credit": 0,
    "code": "1.1.1.1",
    "name": "Cash in Banks",
    "groupId": 48,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.331Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      21,
      48,
      101
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": 208,
    "clashflowId": 0,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 1,
    "clashflowObj": null,
    "report": "BS",
    "nameTax": "No Tax",
    "valueTax": 0,
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 102,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": -12192.86,
    "credit": 0,
    "code": "1.1.1.2",
    "name": "Cash on Hand",
    "groupId": 48,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      21,
      48,
      102
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 0,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 10,
    "clashflowObj": null,
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 103,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": -21400,
    "credit": 0,
    "code": "1.1.1.3",
    "name": "Revolving Funds",
    "groupId": 48,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": false,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      21,
      48,
      103
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 0,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 2,
    "clashflowObj": null,
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 104,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": null,
    "credit": 0,
    "code": "1.1.1.4",
    "name": "Petty Cash Funds",
    "groupId": 48,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      21,
      48,
      104
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 0,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 3,
    "clashflowObj": null,
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 105,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": null,
    "credit": 0,
    "code": "1.1.1.5",
    "name": "Undeposited Collections",
    "groupId": 48,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      21,
      48,
      105
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 0,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 4,
    "clashflowObj": null,
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 106,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": null,
    "credit": 0,
    "code": "1.1.2.1",
    "name": "Marketable Securities",
    "groupId": 49,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      21,
      49,
      106
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 107,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": 100,
    "debit": 12200,
    "credit": 0,
    "code": "1.1.3.1",
    "name": "Accounts Receivable - Trade",
    "groupId": 50,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      21,
      50,
      107
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 14,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 108,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": null,
    "code": "1.1.3.2",
    "name": "Allowance for Doubtful Accounts",
    "groupId": 50,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      21,
      50,
      108
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 14,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 109,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": null,
    "credit": 0,
    "code": "1.1.4.1",
    "name": "Cash Advances - Employees",
    "groupId": 51,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      21,
      51,
      109
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 5,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 110,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": null,
    "credit": 0,
    "code": "1.1.4.2",
    "name": "Cash Advances - Others",
    "groupId": 51,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      21,
      51,
      110
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 6,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 111,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": null,
    "credit": 0,
    "code": "1.1.5.1",
    "name": "Inventory",
    "groupId": 52,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      21,
      52,
      111
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 112,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": null,
    "credit": 0,
    "code": "1.1.6.1",
    "name": "Prepaid Insurance",
    "groupId": 53,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      21,
      53,
      112
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 113,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": null,
    "credit": 0,
    "code": "1.1.6.2",
    "name": "Prepaid Rent",
    "groupId": 53,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      21,
      53,
      113
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 114,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": null,
    "credit": 0,
    "code": "1.1.7.1",
    "name": "Input Tax",
    "groupId": 54,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      21,
      54,
      114
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 8,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 115,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": 488.39,
    "credit": 0,
    "code": "1.1.7.2",
    "name": "Creditable Withholding Tax",
    "groupId": 54,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      21,
      54,
      115
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": 208,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 12,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No Tax",
    "valueTax": 0,
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 116,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": null,
    "credit": 0,
    "code": "1.2.1.1",
    "name": "Investment in Stocks",
    "groupId": 55,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      22,
      55,
      116
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 2,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 117,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": null,
    "credit": 0,
    "code": "1.2.2.1",
    "name": "Investment in Bonds",
    "groupId": 56,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      22,
      56,
      117
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 2,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 118,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": null,
    "credit": 0,
    "code": "1.3.1.1",
    "name": "Land",
    "groupId": 57,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      23,
      57,
      118
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 2,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 119,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": null,
    "credit": 0,
    "code": "1.3.2.1",
    "name": "Building",
    "groupId": 58,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      23,
      58,
      119
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 2,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 120,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": null,
    "code": "1.3.2.2",
    "name": "Accumulated Depreciation - Building",
    "groupId": 58,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      23,
      58,
      120
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 2,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 121,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": null,
    "credit": 0,
    "code": "1.3.3.1",
    "name": "Office Equipment",
    "groupId": 59,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      23,
      59,
      121
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 2,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 122,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": null,
    "code": "1.3.3.2",
    "name": "Accumulated Depreciation - Office Equipment",
    "groupId": 59,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      23,
      59,
      122
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 2,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 123,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": null,
    "credit": 0,
    "code": "1.3.4.1",
    "name": "Furniture and Fixtures",
    "groupId": 60,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      23,
      60,
      123
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 2,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 124,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": null,
    "code": "1.3.4.2",
    "name": "Accumulated Depreciation - Furniture and Fixtures",
    "groupId": 60,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      23,
      60,
      124
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 2,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 125,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": null,
    "credit": 0,
    "code": "1.3.5.1",
    "name": "Transportation Equipment",
    "groupId": 61,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      23,
      61,
      125
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 2,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 126,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": 100,
    "debit": 0,
    "credit": 100,
    "code": "1.3.5.2",
    "name": "Accumulated Depreciation - Transportation Equipment",
    "groupId": 61,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      23,
      61,
      126
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 2,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 127,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": null,
    "credit": 0,
    "code": "1.4.1.1",
    "name": "Copyright",
    "groupId": 62,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      24,
      62,
      127
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 2,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 128,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": null,
    "credit": 0,
    "code": "1.4.2.1",
    "name": "Patents",
    "groupId": 63,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      24,
      63,
      128
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 2,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 129,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": null,
    "credit": 0,
    "code": "1.4.3.1",
    "name": "Research and Development",
    "groupId": 64,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      24,
      64,
      129
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 2,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 130,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": null,
    "credit": 0,
    "code": "1.4.4.1",
    "name": "Trademarks",
    "groupId": 65,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      24,
      65,
      130
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 2,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 131,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": null,
    "credit": 0,
    "code": "1.5.1.1",
    "name": "Bank Guarantee",
    "groupId": 66,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      25,
      66,
      131
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 2,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 2,
      "name": "Investing"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 132,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": null,
    "code": "2.1.1.1",
    "name": "Accounts Payable",
    "groupId": 67,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      2,
      26,
      67,
      132
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 15,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 133,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": null,
    "code": "2.1.1.2",
    "name": "Credit Cards",
    "groupId": 67,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      2,
      26,
      67,
      133
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 7,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 134,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": null,
    "code": "2.1.2.1",
    "name": "Accrued Expenses",
    "groupId": 68,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      2,
      26,
      68,
      134
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 135,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": null,
    "code": "2.1.3.1",
    "name": "Notes Payable",
    "groupId": 69,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      2,
      26,
      69,
      135
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 136,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": null,
    "code": "2.1.4.1",
    "name": "Salaries Payable",
    "groupId": 70,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      2,
      26,
      70,
      136
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 137,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": null,
    "code": "2.1.4.2",
    "name": "Employee Reimbursements",
    "groupId": 70,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      2,
      26,
      70,
      137
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 9,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 138,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": null,
    "code": "2.1.5.1",
    "name": "Salaries Statutory Payable",
    "groupId": 71,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      2,
      26,
      71,
      138
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 139,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": null,
    "code": "2.1.6.1",
    "name": "Direct Deposit Liabilities",
    "groupId": 72,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      2,
      26,
      72,
      139
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 140,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": null,
    "code": "2.2.1.1",
    "name": "Output Tax",
    "groupId": 73,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": 1,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": "76",
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": "2022-07-20T02:24:56.626Z",
    "number": null,
    "filePath": [
      2,
      26,
      73,
      140
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 11,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 141,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": null,
    "code": "2.2.1.2",
    "name": "Withholding Tax",
    "groupId": 73,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      2,
      26,
      73,
      141
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 13,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 142,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": null,
    "code": "2.2.1.3",
    "name": "Withholding Tax on Compensation",
    "groupId": 73,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      2,
      26,
      73,
      142
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 13,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 143,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": null,
    "code": "2.3.1.1",
    "name": "Long Term Payable",
    "groupId": 74,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      2,
      27,
      74,
      143
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 3,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 3,
      "name": "Financing"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 144,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": null,
    "code": "2.4.1.1",
    "name": "Other Liabilities",
    "groupId": 75,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      2,
      28,
      75,
      144
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 3,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 3,
      "name": "Financing"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 145,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": 205936.62,
    "code": "3.1.1.1",
    "name": "Opening Balance Equity",
    "groupId": 76,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      3,
      29,
      76,
      145
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 3,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 3,
      "name": "Financing"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 146,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": null,
    "code": "3.2.1.1",
    "name": "Owner's Equity",
    "groupId": 77,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      3,
      30,
      77,
      146
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 3,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 3,
      "name": "Financing"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 147,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": null,
    "credit": 0,
    "code": "3.2.2.1",
    "name": "Owner's Withdrawal",
    "groupId": 78,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      3,
      30,
      78,
      147
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 3,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 3,
      "name": "Financing"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 148,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": null,
    "code": "3.3.1.1",
    "name": "Partner's Capital",
    "groupId": 79,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      3,
      31,
      79,
      148
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 3,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 3,
      "name": "Financing"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 149,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": null,
    "credit": 0,
    "code": "3.3.2.1",
    "name": "Partner's Withdrawal",
    "groupId": 80,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      3,
      31,
      80,
      149
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 3,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 3,
      "name": "Financing"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 150,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": null,
    "code": "3.4.1.1",
    "name": "Capital Stock",
    "groupId": 81,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      3,
      32,
      81,
      150
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 3,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 3,
      "name": "Financing"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 151,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": null,
    "code": "3.5.1.1",
    "name": "Net Current Earnings",
    "groupId": 82,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      3,
      33,
      82,
      151
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 3,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 3,
      "name": "Financing"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 152,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": null,
    "code": "3.5.1.2",
    "name": "Retained Earnings",
    "groupId": 82,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": null,
    "taxId": null,
    "indelible": true,
    "active": true,
    "createdBy": null,
    "updatedBy": null,
    "createdDate": "2022-07-18T05:54:54.332Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      3,
      33,
      82,
      152
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 3,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 3,
      "name": "Financing"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 201,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": null,
    "credit": 0,
    "code": "1.1.1.2.1",
    "name": "COH USD",
    "groupId": 48,
    "description": null,
    "remarks": null,
    "parentId": 102,
    "currencyId": 1,
    "accountCurrencyId": 6,
    "taxId": null,
    "indelible": false,
    "active": true,
    "createdBy": "6",
    "updatedBy": null,
    "createdDate": "2022-07-18T07:05:46.714Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      21,
      48,
      102,
      201
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": 202,
    "clashflowId": null,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 10,
    "clashflowObj": null,
    "report": "BS",
    "nameTax": "VAT - Construction 12%",
    "valueTax": 12,
    "currencyName": "US Dollar",
    "currencycode": "USD"
  },
  {
    "id": 202,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": 107.14,
    "credit": 0,
    "code": "1.1.7.1.1",
    "name": "VAT - Construction 12%",
    "groupId": 54,
    "description": null,
    "remarks": null,
    "parentId": 114,
    "currencyId": 1,
    "accountCurrencyId": 1,
    "taxId": 146,
    "indelible": false,
    "active": true,
    "createdBy": "5",
    "updatedBy": "76",
    "createdDate": "2022-07-18T07:36:03.879Z",
    "updatedDate": "2022-07-19T05:10:01.739Z",
    "number": null,
    "filePath": [
      1,
      21,
      54,
      114,
      202
    ],
    "entityType": "account",
    "taxTypeId": 1,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 8,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "",
    "valueTax": 12,
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 205,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": 2412,
    "credit": 0,
    "code": "1.1.7.1.2",
    "name": "Input VAT-Goods other than capital goods 12%",
    "groupId": 54,
    "description": null,
    "remarks": null,
    "parentId": 114,
    "currencyId": 1,
    "accountCurrencyId": 1,
    "taxId": 147,
    "indelible": false,
    "active": true,
    "createdBy": "9",
    "updatedBy": "76",
    "createdDate": "2022-07-18T13:03:48.804Z",
    "updatedDate": "2022-07-19T05:10:18.191Z",
    "number": null,
    "filePath": [
      1,
      21,
      54,
      114,
      205
    ],
    "entityType": "account",
    "taxTypeId": 1,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 8,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "",
    "valueTax": 12,
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 206,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": 8142.86,
    "credit": 0,
    "code": "1.1.7.1.3",
    "name": "Input VAT-Services 12%",
    "groupId": 54,
    "description": null,
    "remarks": null,
    "parentId": 114,
    "currencyId": 1,
    "accountCurrencyId": 1,
    "taxId": 158,
    "indelible": false,
    "active": true,
    "createdBy": "9",
    "updatedBy": "76",
    "createdDate": "2022-07-18T13:05:17.867Z",
    "updatedDate": "2022-07-19T05:10:33.758Z",
    "number": null,
    "filePath": [
      1,
      21,
      54,
      114,
      206
    ],
    "entityType": "account",
    "taxTypeId": 1,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 8,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "",
    "valueTax": 12,
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 207,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": 1000,
    "code": "2.2.1.2.1",
    "name": "Withholding tax Rental 5%",
    "groupId": 73,
    "description": null,
    "remarks": null,
    "parentId": 141,
    "currencyId": 1,
    "accountCurrencyId": 1,
    "taxId": 287,
    "indelible": false,
    "active": true,
    "createdBy": "9",
    "updatedBy": null,
    "createdDate": "2022-07-18T13:17:07.245Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      2,
      26,
      73,
      141,
      207
    ],
    "entityType": "account",
    "taxTypeId": 2,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 13,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "",
    "valueTax": 5,
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 208,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": 0,
    "code": "1.1.7.1.4",
    "name": "Non Taxable 0%",
    "groupId": 54,
    "description": null,
    "remarks": null,
    "parentId": 114,
    "currencyId": 1,
    "accountCurrencyId": 1,
    "taxId": 131,
    "indelible": false,
    "active": true,
    "createdBy": "9",
    "updatedBy": null,
    "createdDate": "2022-07-18T14:13:04.950Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      21,
      54,
      114,
      208
    ],
    "entityType": "account",
    "taxTypeId": 1,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 8,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "",
    "valueTax": 0,
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 209,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": 1060.71,
    "credit": 0,
    "code": "1.1.7.3",
    "name": "Creditable VAT Withheld",
    "groupId": 54,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": 1,
    "taxId": 192,
    "indelible": false,
    "active": true,
    "createdBy": "2",
    "updatedBy": null,
    "createdDate": "2022-07-18T17:26:13.471Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      21,
      54,
      209
    ],
    "entityType": "account",
    "taxTypeId": 1,
    "assignToTaxAccountId": 208,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 16,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "",
    "valueTax": 5,
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 210,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": null,
    "credit": 0,
    "code": "1.1.7.1.6",
    "name": "IV- Cap goods exceeding P1M 12%",
    "groupId": 54,
    "description": null,
    "remarks": null,
    "parentId": 114,
    "currencyId": 1,
    "accountCurrencyId": 1,
    "taxId": 160,
    "indelible": false,
    "active": true,
    "createdBy": "2",
    "updatedBy": "76",
    "createdDate": "2022-07-18T17:43:08.219Z",
    "updatedDate": "2022-07-19T05:14:59.559Z",
    "number": null,
    "filePath": [
      1,
      21,
      54,
      114,
      210
    ],
    "entityType": "account",
    "taxTypeId": 1,
    "assignToTaxAccountId": 202,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 8,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "",
    "valueTax": 12,
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 211,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": null,
    "debit": null,
    "credit": 0,
    "code": "1.1.1.2.1.1",
    "name": "test",
    "groupId": 48,
    "description": null,
    "remarks": null,
    "parentId": 201,
    "currencyId": 1,
    "accountCurrencyId": 1,
    "taxId": null,
    "indelible": false,
    "active": true,
    "createdBy": "2",
    "updatedBy": null,
    "createdDate": "2022-07-18T18:06:56.381Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      21,
      48,
      102,
      201,
      211
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": 210,
    "clashflowId": null,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 10,
    "clashflowObj": null,
    "report": "BS",
    "nameTax": "IV- Cap goods exceeding P1M 12%",
    "valueTax": 12,
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 212,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": 2400,
    "code": "2.2.1.1.1",
    "name": "VAT-Buss on general 12%",
    "groupId": 73,
    "description": null,
    "remarks": null,
    "parentId": 140,
    "currencyId": 1,
    "accountCurrencyId": 1,
    "taxId": 148,
    "indelible": false,
    "active": true,
    "createdBy": "76",
    "updatedBy": "76",
    "createdDate": "2022-07-19T01:50:11.325Z",
    "updatedDate": "2022-07-19T05:15:50.534Z",
    "number": null,
    "filePath": [
      2,
      26,
      73,
      140,
      212
    ],
    "entityType": "account",
    "taxTypeId": 1,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 11,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "",
    "valueTax": 12,
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 313,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": null,
    "code": "2.2.1.1.2",
    "name": "VAT - Construction 12%",
    "groupId": 73,
    "description": null,
    "remarks": null,
    "parentId": 140,
    "currencyId": 1,
    "accountCurrencyId": 1,
    "taxId": 146,
    "indelible": false,
    "active": true,
    "createdBy": "76",
    "updatedBy": null,
    "createdDate": "2022-07-19T06:08:36.428Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      2,
      26,
      73,
      140,
      313
    ],
    "entityType": "account",
    "taxTypeId": 1,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 11,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "",
    "valueTax": 12,
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 314,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": 15454.55,
    "debit": 15254.55,
    "credit": 0,
    "code": "1.1.1.1.1",
    "name": "CIB USD",
    "groupId": 48,
    "description": null,
    "remarks": null,
    "parentId": 101,
    "currencyId": 1,
    "accountCurrencyId": 6,
    "taxId": null,
    "indelible": false,
    "active": true,
    "createdBy": "6",
    "updatedBy": null,
    "createdDate": "2022-07-19T06:29:10.322Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      21,
      48,
      101,
      314
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": null,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 1,
    "clashflowObj": null,
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "US Dollar",
    "currencycode": "USD"
  },
  {
    "id": 315,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": 15454.55,
    "debit": 0,
    "credit": 15454.55,
    "code": "2.1.1.1.1",
    "name": "AP / USD",
    "groupId": 67,
    "description": null,
    "remarks": null,
    "parentId": 132,
    "currencyId": 1,
    "accountCurrencyId": 6,
    "taxId": null,
    "indelible": false,
    "active": true,
    "createdBy": "6",
    "updatedBy": null,
    "createdDate": "2022-07-19T06:57:37.314Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      2,
      26,
      67,
      132,
      315
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 15,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "US Dollar",
    "currencycode": "USD"
  },
  {
    "id": 316,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": 20000,
    "debit": 20000,
    "credit": 0,
    "code": "1.1.1.2.1.1.1",
    "name": "test2",
    "groupId": 48,
    "description": null,
    "remarks": null,
    "parentId": 211,
    "currencyId": 1,
    "accountCurrencyId": 1,
    "taxId": null,
    "indelible": false,
    "active": true,
    "createdBy": "5",
    "updatedBy": null,
    "createdDate": "2022-07-19T07:47:44.843Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      21,
      48,
      102,
      201,
      211,
      316
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": 202,
    "clashflowId": null,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 10,
    "clashflowObj": null,
    "report": "BS",
    "nameTax": "VAT - Construction 12%",
    "valueTax": 12,
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  },
  {
    "id": 317,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": 37545.07,
    "debit": 37545.07,
    "credit": 0,
    "code": "1.1.1.1.2",
    "name": "CIB - EURO",
    "groupId": 48,
    "description": null,
    "remarks": null,
    "parentId": 101,
    "currencyId": 1,
    "accountCurrencyId": 2,
    "taxId": null,
    "indelible": false,
    "active": true,
    "createdBy": "6",
    "updatedBy": null,
    "createdDate": "2022-07-20T01:43:47.275Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      21,
      48,
      101,
      317
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": 208,
    "clashflowId": null,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 1,
    "clashflowObj": null,
    "report": "BS",
    "nameTax": "No Tax",
    "valueTax": 0,
    "currencyName": "Euro",
    "currencycode": "EUR"
  },
  {
    "id": 318,
    "DRCRCode": "DR",
    "companyId": 90,
    "amount": 148391.55,
    "debit": 148391.55,
    "credit": 0,
    "code": "1.1.3.3",
    "name": "Accounts Receivable - Trade EURO",
    "groupId": 50,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": 2,
    "taxId": null,
    "indelible": false,
    "active": true,
    "createdBy": "6",
    "updatedBy": null,
    "createdDate": "2022-07-20T01:51:41.901Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      1,
      21,
      50,
      318
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 0,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Euro",
    "currencycode": "EUR"
  },
  {
    "id": 519,
    "DRCRCode": "CR",
    "companyId": 90,
    "amount": null,
    "debit": 0,
    "credit": null,
    "code": "2.2.1.7",
    "name": "Sales Tax Payable",
    "groupId": 73,
    "description": null,
    "remarks": null,
    "parentId": null,
    "currencyId": 1,
    "accountCurrencyId": 1,
    "taxId": null,
    "indelible": false,
    "active": true,
    "createdBy": "76",
    "updatedBy": null,
    "createdDate": "2022-07-20T08:27:00.605Z",
    "updatedDate": null,
    "number": null,
    "filePath": [
      2,
      26,
      73,
      519
    ],
    "entityType": "account",
    "taxTypeId": null,
    "assignToTaxAccountId": null,
    "clashflowId": 1,
    "isBankAccount": false,
    "isCreditCardAccount": false,
    "finDocName": "BALANCE SHEET",
    "accountTypeId": 17,
    "clashflowObj": {
      "id": 1,
      "name": "Operating"
    },
    "report": "BS",
    "nameTax": "No tax",
    "currencyName": "Australian Dollar",
    "currencycode": "AUD"
  }
]
